server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_db
    username: myuser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enable: true