server:
  port: 8082

spring:
  application:
    name: client-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true

cloud:
  config:
    enabled: true
    discovery:
      enabled: true
